# Generated by Django 3.1.1 on 2020-09-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='Politic', on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
