# Generated by Django 3.1.1 on 2020-09-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
